spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@dovb_high?TNS_ADMIN=./src/main/resources/Wallet_DOVB
        username: admin
        password: "!Qkswodms0626"


    jpa:
        hibernate:
            ddl-auto: none
        properties:
          hibernate:
              format_sql: true
              show_sql: true
        database: oracle

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

logging:
    level:
      org.hibernate.sql: error

server:
    port: 8080

swagger:
    port: 8088
    paths: |
        /swagger-ui.html,
        /webjars/springfox-swagger-ui/**/*,
        /swagger-resources,
        /swagger-resources/**/*,
        /v2/api-docs