server:
  port: 8080

spring:
  #  config:
  #    activate:
  #      on-profile: prod

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@dovb_high?TNS_ADMIN=./src/main/resources/Wallet_DOVB
    username: admin
    password: "!Qkswodms7043"


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    database: oracle

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  fcm:
    key:
      path: ./google_project.json
      scope: https://www.googleapis.com/auth/cloud-platform

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
#          descriptor:
#    org.hibernate.sql: error
#    org.hibernate.type: error
#    org.hibernate.type.descriptor.sql: trace
