version: 2.1

jobs:
  build:
      docker:
        - image: cimg/openjdk:17.0.4
      steps:
        - run:
            name: Deploy Over SSH
            command: ./gradlew build

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh ubuntu@152.67.212.253 "./deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
          branches:
            only: main # only deploy on the main branch


